components:
  - name: Dashboard
    test_config:
      robot_tags: ['Dashboard']
      platform: Jenkins
      job_url: ''
    repositories:
      - name: odh-dashboard
        src:
          url: https://github.com/opendatahub-io/odh-dashboard.git
          branch: sync-test
        dest:
          url: https://github.com/red-hat-data-services/odh-dashboard-sync.git
          branch: main
        ignore_files: [".env", ".env.test"]
      - name: odh-operator
        src:
          url: https://github.com/opendatahub-io/opendatahub-operator.git
          branch: sync-test
        dest:
          url: https://github.com/red-hat-data-services/opendatahub-operator-sync.git
          branch: main